print("MI PRIMER PROGRAMA REALIZADO EN PYTHON")
print("--------------------------------------")
print()
print("Realizado po Edwin Ganán \n Paralelo Septimo C")
print("Repaso de Modulo 1",end="")
print("Principios básicos en Python")
print("Aprenderemos"," Temas muy interesantes",sep="-")
print()
print("Ejemplo","Número","Uno",sep="_",end="*")
print("Poniendo separador y Asterisco")
print()
print("Vamos a sumar")
print(2+2)
print("Vamos Potencia")
print(2**3)
print("Vamos Multiplicación")
print(2*4)
print("Vamos a dividir")
print(10/2)
print("Vamos A División entera")
print(5 // 3)